### ISSUE TITLE
Add bower.json

### ISSUE THREAD

**Issue by thijstriemstra** [videojs/grunt-videojs-languages#1]
Is it possible to add a `bower.json` or this project so I can use a version nr instead of:

``` javascript
"grunt-videojs-languages": "git://github.com/videojs/grunt-videojs-languages.git"
```

Can make a PR after feedback.

**Comment by gkatsev** [comment]
This project is available on npm: https://www.npmjs.com/package/grunt-videojs-languages. I don't really see the usecase of adding a grunt project to bower.

**Comment by thijstriemstra** [comment]
All other packages work fine with bower:

``` javascript
"devDependencies": {
    "grunt": "~0.4.5",
    "grunt-contrib-jshint": "~0.10.0",
    "grunt-contrib-watch": "~0.6.1",
    "grunt-contrib-concat": "~0.4.0",
    "grunt-contrib-uglify": "~0.5.0",
    "grunt-contrib-cssmin": "~0.11.0",
    "grunt-videojs-languages": "git://github.com/videojs/grunt-videojs-languages.git"
  }
```

**Comment by heff** [comment]
​What does it looks like to build a grunt file with bower-included scripts?
Is there a loadBowerTasks function?

**Comment by thijstriemstra** [comment]
Not sure. Bower is just a package manager. I'm using require.js optimizer to package my app for example, and bower for dependencies. I simply want to be able to pull in the dependency using bower. I guess this would work as well to get a specific tag:

``` javascript
"grunt-videojs-languages": "git://github.com/videojs/grunt-videojs-languages.git#0.0.4"
```

Just trying to make life easier for (bower) users :)

**Comment by gkatsev** [comment]
This dependency isn't used client-side. It's a server-side grunt plugin for building language items. I really don't think this needs a bower.json file nor that it would help bower users to have it.

**Comment by thijstriemstra** [comment]
Well plugin developers use this package to provide localization. So it's more useful for videojs (bower) plugin developers. But feel free to close this if you think the extra maintainance of such a file in your project is not worth it.

**Comment by gkatsev** [comment]
Yes, they can use it, but it has to be used through grunt and I'm not sure you can get grunt working through bower.

**Comment by thijstriemstra** [comment]
Yeah, there must be something I'm misunderstanding because the other dependencies I mentioned also don't have a bower.json file in their repository. But still they dont cause errors when running `bower install`, as opposed to `grunt-videojs-languages` (unless you use the git repo path). Oh well.

**Comment by heff** [comment]
​What are the errors that it throws?

**Comment by thijstriemstra** [comment]
```
bower ENOTFOUND     Package grunt-videojs-languages not found
```

It's not registered, bower doesn't know about it. The only way to register it is using a bower file. Maybe you should make one, add minimum of settings (so no version nr), register it with `bower register` and you're done?

**Comment by thijstriemstra** [comment]
Ha.

```
$ bower register grunt-videojs-languages https://github.com/videojs/grunt-videojs-languages.git
bower convert       Converted https://github.com/videojs/grunt-videojs-languages.git to git://github.com/videojs/grunt-videojs-languages.git
bower resolve       git://github.com/videojs/grunt-videojs-languages.git#*
bower download      https://github.com/videojs/grunt-videojs-languages/archive/v0.0.4.tar.gz
bower extract       grunt-videojs-languages#* archive.tar.gz
bower invalid-meta  grunt-videojs-languages is missing "main" entry in bower.json
bower invalid-meta  grunt-videojs-languages is missing "ignore" entry in bower.json
bower resolved      git://github.com/videojs/grunt-videojs-languages.git#0.0.4
? Registering a package will make it installable via the registry (https://bower.herokuapp.com), continue?: Yesn) yes
bower register      git://github.com/videojs/grunt-videojs-languages.git

Package grunt-videojs-languages registered successfully!
All valid semver tags on git://github.com/videojs/grunt-videojs-languages.git will be available as versions.
To publish a new version, just release a valid semver tag.

Run bower info grunt-videojs-languages to list the available versions.
```

**Comment by thijstriemstra** [comment]
Fixed, sweet! Thanks for the discussion.

```
$ bower install
bower cached        git://github.com/collab-project/videojs-wavesurfer.git#0.9.0
bower validate      0.9.0 against git://github.com/collab-project/videojs-wavesurfer.git#>=0.9.0
bower cached        git://github.com/videojs/grunt-videojs-languages.git#0.0.4
bower validate      0.0.4 against git://github.com/videojs/grunt-videojs-languages.git#~0.0.4
bower install       videojs-wavesurfer#0.9.0
bower install       grunt-videojs-languages#0.0.4

videojs-wavesurfer#0.9.0 bower_components/videojs-wavesurfer
├── video.js#4.11.3
└── wavesurfer.js#1.0.10

grunt-videojs-languages#0.0.4 bower_components/grunt-videojs-languages
```

**Comment by heff** [comment]
Ha! Nice.
